run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - errcheck
    - gocritic
    - gosec
    - misspell
    - revive

linters-settings:
  gosec:
    excludes:
      - G204 # Subprocess launched with variable - safe in controlled context
  revive:
    rules:
      - name: indent-error-flow
        severity: warning
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  exclude:
    - "error return value not checked.*(Close|Log|Printf)"
    - "should have comment or be unexported"

