project_name: dcs
before:
  hooks:
    - go mod download
builds:
  - id: dcs
    main: ./
    binary: dcs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: ["-trimpath"]
    ldflags:
      - -s -w
archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
brews:
  - name: dcs
    repository:
      owner: KNIF
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    homepage: https://github.com/KNIF/docker-compose-secrets
    description: Manage Docker Compose secrets from HashiCorp Vault
checksum:
  name_template: "checksums.txt"
changelog:
  sort: desc
  use: git