project_name: dcs
before:
  hooks:
    - go mod download
builds:
  - id: dcs
    main: ./
    binary: dcs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: ["-trimpath"]
    ldflags:
      - -s -w
archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
changelog:
  sort: desc
  use: git