name: Build binaries on master
on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          BIN_NAME=dcs
          if [ "${{ matrix.goos }}" = "windows" ]; then BIN_NAME=dcs.exe; fi
          go build -trimpath -ldflags "-s -w" -o dist/${BIN_NAME}-${{ matrix.goos }}-${{ matrix.goarch }} ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dcs-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/dcs-${{ matrix.goos }}-${{ matrix.goarch }}
